### ISSUE TITLE
window.less     .modifyVars是在哪里配置的

### ISSUE THREAD

**Issue by azz1123** [bestRenekton/demos#1]
window.less
    .modifyVars(
      {
        '@primary-color': '#ee5e7b',
        '@link-color': '#ee5e7b',
  	  '@btn-primary-bg': 'ee5e7b',
      }
    )
    .then(() => { })
    .catch(error => {
      message.error(`Failed to update theme`);
    });

**Comment by bestRenekton** [comment]
1.安装cnpm i antd-theme-generator --save
2.html里面需要
```html
<link rel="stylesheet/less" type="text/css" href="static/color.less" /> //主要是这个起作用
    <script>
        window.less = {
            async: false,
            env: 'production'
        };
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
```
3.根目录添加color.js
4.src添加styles文件夹，里面有vars.less和main.less
5.package.json修改，为了每次自动node color.js，所以scripts里面修改下
```json
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node color &&  webpack-dev-server --config webpack.config.dev.js", 
    "start": "npm run dev",
    "build": "node color && webpack --config webpack.config.prod.js"
  },
```
6.然后window.less.modifyVars就可以生效了

**Comment by sine-hx** [comment]
window.less.modifyVars是放哪里的呢？

**Comment by bestRenekton** [comment]
> window.less.modifyVars是放哪里的呢？

你需要执行的地方啊。。
